# Meta Data for SEO

## Homepage
title = "GP Docs & Blog"
titleSeparator = "-"
titleAddition = "About Galactic Polymath and how to use our site"
description = "Galactic Polymath blog posts and documentation. Learn about who we are and how we do."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["doks.png"]
ogLocale = "en_US"
domainTLD = "doks.netlify.app"
titleHome = "Doks Theme"

## Twitter Cards
twitterSite = "@galacticPM"
twitterCreator = "@mattwilkinsbio"

# Search
mainSections = ["blog", "docs"]

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Galactic Polymath Documentation"
schemaAuthor = "Matt Wilkins"
schemaAuthorTwitter = "https://twitter.com/mattwilkinsbio"
schemaAuthorLinkedIn = "https://www.linkedin.com/in/mattwilkinsphd/"
schemaAuthorGitHub = "https://github.com/drwilkins"
schemaLocale = "en-US"
schemaLogo = "logo-doks.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "doks.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/galacticPM"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/galacticPM/gp-docs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = true

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
avatarLimit= "100"
smallLimit = "300"

# Footer
footer = "Powered by <a href=\"https://www.netlify.com/\">Netlify</a>, <a href=\"https://gohugo.io/\">Hugo</a>, and <a href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2020-2021 Henk Verlinde"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\">Check out Doks v0.2</a>"

# Edit Page
docsRepo = "https://github.com/h-enk/doks"
docsRepoBranch = "master"
editPage = false

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  collapsibleSidebar = true
  multilingualMode = false
  docsVersioning = false
